import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Footer} from "./components/footer/footer"
import {Header} from "./components/header/header"
import {StoreProvider} from "../lib/StoreProvider"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="layout">
        <Header className="layout__header"/>
         <main className="layout__main">
           {children}
         </main>
        <Footer className="layout__footer"/>
      </body>
      </StoreProvider>
    </html>
  );
}
